--
-- PostgreSQL database dump
--

\restrict fDRYSexOubs91007hT39zqKSMcIXLQzyuueVtOhi7RICSjpXPvqhhRhnN4hxulY

-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: asignaciones_permisos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.asignaciones_permisos (
    id_asignacion integer NOT NULL,
    id_funcionario integer NOT NULL,
    id_tipo_permiso integer NOT NULL,
    periodo integer NOT NULL,
    dias_asignados numeric(6,2) DEFAULT 0,
    horas_asignadas numeric(6,2) DEFAULT 0,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_asignaciones_dias CHECK (((dias_asignados IS NULL) OR (dias_asignados >= (0)::numeric))),
    CONSTRAINT chk_asignaciones_horas CHECK (((horas_asignadas IS NULL) OR (horas_asignadas >= (0)::numeric)))
);


--
-- Name: asignaciones_permisos_id_asignacion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.asignaciones_permisos ALTER COLUMN id_asignacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asignaciones_permisos_id_asignacion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auditoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auditoria (
    id_auditoria integer NOT NULL,
    id_usuario integer NOT NULL,
    accion character varying(100) NOT NULL,
    entidad character varying(100) NOT NULL,
    id_registro integer,
    detalle text,
    direccion_ip character varying(45),
    fecha_evento timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: auditoria_id_auditoria_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auditoria ALTER COLUMN id_auditoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auditoria_id_auditoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: estados_solicitud; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estados_solicitud (
    id_estado integer NOT NULL,
    nombre character varying(50) NOT NULL,
    descripcion text
);


--
-- Name: estados_solicitud_id_estado_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.estados_solicitud ALTER COLUMN id_estado ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estados_solicitud_id_estado_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: funcionarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.funcionarios (
    id_funcionario integer NOT NULL,
    id_unidad integer NOT NULL,
    nombres character varying(100) NOT NULL,
    apellido_paterno character varying(100) NOT NULL,
    apellido_materno character varying(100),
    correo_institucional character varying(150) NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: funcionarios_id_funcionario_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.funcionarios ALTER COLUMN id_funcionario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.funcionarios_id_funcionario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: historial_solicitud; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.historial_solicitud (
    id_historial integer NOT NULL,
    id_solicitud integer NOT NULL,
    id_estado integer NOT NULL,
    id_usuario_accion integer,
    fecha_cambio timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    observacion text
);


--
-- Name: historial_solicitud_id_historial_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.historial_solicitud ALTER COLUMN id_historial ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.historial_solicitud_id_historial_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notificaciones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notificaciones (
    id_notificacion integer NOT NULL,
    id_usuario integer NOT NULL,
    id_solicitud integer,
    tipo character varying(50) NOT NULL,
    mensaje text NOT NULL,
    leida boolean DEFAULT false NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: notificaciones_id_notificacion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notificaciones ALTER COLUMN id_notificacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificaciones_id_notificacion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permisos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permisos (
    id_permiso integer NOT NULL,
    id_solicitud integer,
    id_funcionario integer NOT NULL,
    id_tipo_permiso integer NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_termino date NOT NULL,
    modalidad character varying(30) NOT NULL,
    hora_inicio time without time zone,
    hora_termino time without time zone,
    cantidad_dias numeric(6,2),
    cantidad_horas numeric(6,2),
    origen character varying(30) DEFAULT 'SOLICITUD'::character varying NOT NULL,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_permisos_cantidad_dias CHECK (((cantidad_dias IS NULL) OR (cantidad_dias >= (0)::numeric))),
    CONSTRAINT chk_permisos_cantidad_horas CHECK (((cantidad_horas IS NULL) OR (cantidad_horas >= (0)::numeric))),
    CONSTRAINT chk_permisos_fechas CHECK ((fecha_termino >= fecha_inicio))
);


--
-- Name: permisos_id_permiso_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.permisos ALTER COLUMN id_permiso ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permisos_id_permiso_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id_rol integer NOT NULL,
    nombre character varying(50) NOT NULL,
    descripcion text,
    activo boolean DEFAULT true NOT NULL
);


--
-- Name: roles_id_rol_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id_rol ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_rol_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solicitudes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.solicitudes (
    id_solicitud integer NOT NULL,
    id_funcionario integer NOT NULL,
    id_tipo_permiso integer NOT NULL,
    id_estado integer NOT NULL,
    fecha_solicitud timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_termino date NOT NULL,
    modalidad character varying(30) NOT NULL,
    hora_inicio time without time zone,
    hora_termino time without time zone,
    cantidad_dias numeric(6,2),
    cantidad_horas numeric(6,2),
    observacion text,
    requiere_reemplazo boolean DEFAULT false NOT NULL,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_solicitudes_cantidad_dias CHECK (((cantidad_dias IS NULL) OR (cantidad_dias >= (0)::numeric))),
    CONSTRAINT chk_solicitudes_cantidad_horas CHECK (((cantidad_horas IS NULL) OR (cantidad_horas >= (0)::numeric))),
    CONSTRAINT chk_solicitudes_fechas CHECK ((fecha_termino >= fecha_inicio))
);


--
-- Name: solicitudes_id_solicitud_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.solicitudes ALTER COLUMN id_solicitud ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solicitudes_id_solicitud_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipos_permiso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tipos_permiso (
    id_tipo_permiso integer NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text,
    unidad_control character varying(20) NOT NULL,
    requiere_horario boolean DEFAULT false NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


--
-- Name: tipos_permiso_id_tipo_permiso_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tipos_permiso ALTER COLUMN id_tipo_permiso ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipos_permiso_id_tipo_permiso_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: unidades; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.unidades (
    id_unidad integer NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text,
    activo boolean DEFAULT true NOT NULL
);


--
-- Name: unidades_id_unidad_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.unidades ALTER COLUMN id_unidad ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.unidades_id_unidad_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    id_usuario integer NOT NULL,
    id_funcionario integer NOT NULL,
    id_rol integer NOT NULL,
    password_hash character varying(255) NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    ultimo_acceso timestamp without time zone,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: asignaciones_permisos asignaciones_permisos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asignaciones_permisos
    ADD CONSTRAINT asignaciones_permisos_pkey PRIMARY KEY (id_asignacion);


--
-- Name: auditoria auditoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auditoria
    ADD CONSTRAINT auditoria_pkey PRIMARY KEY (id_auditoria);


--
-- Name: estados_solicitud estados_solicitud_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_solicitud
    ADD CONSTRAINT estados_solicitud_nombre_key UNIQUE (nombre);


--
-- Name: estados_solicitud estados_solicitud_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_solicitud
    ADD CONSTRAINT estados_solicitud_pkey PRIMARY KEY (id_estado);


--
-- Name: funcionarios funcionarios_correo_institucional_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.funcionarios
    ADD CONSTRAINT funcionarios_correo_institucional_key UNIQUE (correo_institucional);


--
-- Name: funcionarios funcionarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.funcionarios
    ADD CONSTRAINT funcionarios_pkey PRIMARY KEY (id_funcionario);


--
-- Name: historial_solicitud historial_solicitud_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_solicitud
    ADD CONSTRAINT historial_solicitud_pkey PRIMARY KEY (id_historial);


--
-- Name: notificaciones notificaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT notificaciones_pkey PRIMARY KEY (id_notificacion);


--
-- Name: permisos permisos_id_solicitud_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permisos
    ADD CONSTRAINT permisos_id_solicitud_key UNIQUE (id_solicitud);


--
-- Name: permisos permisos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permisos
    ADD CONSTRAINT permisos_pkey PRIMARY KEY (id_permiso);


--
-- Name: roles roles_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_nombre_key UNIQUE (nombre);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id_rol);


--
-- Name: solicitudes solicitudes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitudes
    ADD CONSTRAINT solicitudes_pkey PRIMARY KEY (id_solicitud);


--
-- Name: tipos_permiso tipos_permiso_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipos_permiso
    ADD CONSTRAINT tipos_permiso_nombre_key UNIQUE (nombre);


--
-- Name: tipos_permiso tipos_permiso_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipos_permiso
    ADD CONSTRAINT tipos_permiso_pkey PRIMARY KEY (id_tipo_permiso);


--
-- Name: unidades unidades_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unidades
    ADD CONSTRAINT unidades_nombre_key UNIQUE (nombre);


--
-- Name: unidades unidades_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unidades
    ADD CONSTRAINT unidades_pkey PRIMARY KEY (id_unidad);


--
-- Name: asignaciones_permisos uq_asignacion_funcionario_tipo_periodo; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asignaciones_permisos
    ADD CONSTRAINT uq_asignacion_funcionario_tipo_periodo UNIQUE (id_funcionario, id_tipo_permiso, periodo);


--
-- Name: usuarios usuarios_id_funcionario_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_id_funcionario_key UNIQUE (id_funcionario);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario);


--
-- Name: idx_auditoria_fecha_evento; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auditoria_fecha_evento ON public.auditoria USING btree (fecha_evento);


--
-- Name: idx_auditoria_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auditoria_usuario ON public.auditoria USING btree (id_usuario);


--
-- Name: idx_funcionarios_unidad; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_funcionarios_unidad ON public.funcionarios USING btree (id_unidad);


--
-- Name: idx_historial_fecha_cambio; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_historial_fecha_cambio ON public.historial_solicitud USING btree (fecha_cambio);


--
-- Name: idx_historial_solicitud; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_historial_solicitud ON public.historial_solicitud USING btree (id_solicitud);


--
-- Name: idx_notificaciones_usuario_leida; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notificaciones_usuario_leida ON public.notificaciones USING btree (id_usuario, leida);


--
-- Name: idx_permisos_fecha_inicio; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_permisos_fecha_inicio ON public.permisos USING btree (fecha_inicio);


--
-- Name: idx_permisos_funcionario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_permisos_funcionario ON public.permisos USING btree (id_funcionario);


--
-- Name: idx_permisos_tipo_permiso; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_permisos_tipo_permiso ON public.permisos USING btree (id_tipo_permiso);


--
-- Name: idx_solicitudes_estado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_solicitudes_estado ON public.solicitudes USING btree (id_estado);


--
-- Name: idx_solicitudes_fecha_inicio; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_solicitudes_fecha_inicio ON public.solicitudes USING btree (fecha_inicio);


--
-- Name: idx_solicitudes_fecha_solicitud; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_solicitudes_fecha_solicitud ON public.solicitudes USING btree (fecha_solicitud);


--
-- Name: idx_solicitudes_funcionario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_solicitudes_funcionario ON public.solicitudes USING btree (id_funcionario);


--
-- Name: idx_solicitudes_tipo_permiso; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_solicitudes_tipo_permiso ON public.solicitudes USING btree (id_tipo_permiso);


--
-- Name: idx_usuarios_rol; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuarios_rol ON public.usuarios USING btree (id_rol);


--
-- Name: asignaciones_permisos fk_asignaciones_funcionario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asignaciones_permisos
    ADD CONSTRAINT fk_asignaciones_funcionario FOREIGN KEY (id_funcionario) REFERENCES public.funcionarios(id_funcionario) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: asignaciones_permisos fk_asignaciones_tipo_permiso; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asignaciones_permisos
    ADD CONSTRAINT fk_asignaciones_tipo_permiso FOREIGN KEY (id_tipo_permiso) REFERENCES public.tipos_permiso(id_tipo_permiso) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: auditoria fk_auditoria_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auditoria
    ADD CONSTRAINT fk_auditoria_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: funcionarios fk_funcionarios_unidad; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.funcionarios
    ADD CONSTRAINT fk_funcionarios_unidad FOREIGN KEY (id_unidad) REFERENCES public.unidades(id_unidad) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: historial_solicitud fk_historial_estado; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_solicitud
    ADD CONSTRAINT fk_historial_estado FOREIGN KEY (id_estado) REFERENCES public.estados_solicitud(id_estado) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: historial_solicitud fk_historial_solicitud; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_solicitud
    ADD CONSTRAINT fk_historial_solicitud FOREIGN KEY (id_solicitud) REFERENCES public.solicitudes(id_solicitud) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: historial_solicitud fk_historial_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_solicitud
    ADD CONSTRAINT fk_historial_usuario FOREIGN KEY (id_usuario_accion) REFERENCES public.usuarios(id_usuario) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: notificaciones fk_notificaciones_solicitud; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT fk_notificaciones_solicitud FOREIGN KEY (id_solicitud) REFERENCES public.solicitudes(id_solicitud) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: notificaciones fk_notificaciones_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT fk_notificaciones_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: permisos fk_permisos_funcionario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permisos
    ADD CONSTRAINT fk_permisos_funcionario FOREIGN KEY (id_funcionario) REFERENCES public.funcionarios(id_funcionario) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: permisos fk_permisos_solicitud; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permisos
    ADD CONSTRAINT fk_permisos_solicitud FOREIGN KEY (id_solicitud) REFERENCES public.solicitudes(id_solicitud) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: permisos fk_permisos_tipo_permiso; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permisos
    ADD CONSTRAINT fk_permisos_tipo_permiso FOREIGN KEY (id_tipo_permiso) REFERENCES public.tipos_permiso(id_tipo_permiso) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: solicitudes fk_solicitudes_estado; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitudes
    ADD CONSTRAINT fk_solicitudes_estado FOREIGN KEY (id_estado) REFERENCES public.estados_solicitud(id_estado) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: solicitudes fk_solicitudes_funcionario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitudes
    ADD CONSTRAINT fk_solicitudes_funcionario FOREIGN KEY (id_funcionario) REFERENCES public.funcionarios(id_funcionario) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: solicitudes fk_solicitudes_tipo_permiso; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitudes
    ADD CONSTRAINT fk_solicitudes_tipo_permiso FOREIGN KEY (id_tipo_permiso) REFERENCES public.tipos_permiso(id_tipo_permiso) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: usuarios fk_usuarios_funcionario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT fk_usuarios_funcionario FOREIGN KEY (id_funcionario) REFERENCES public.funcionarios(id_funcionario) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: usuarios fk_usuarios_rol; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT fk_usuarios_rol FOREIGN KEY (id_rol) REFERENCES public.roles(id_rol) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

\unrestrict fDRYSexOubs91007hT39zqKSMcIXLQzyuueVtOhi7RICSjpXPvqhhRhnN4hxulY

